In [1]:
# haandle data
import json
import operator
import collections

In [2]:
# handle table data
import numpy as np
import pandas as pd

In [3]:
from sklearn import svm
from sklearn import model_selection 

In [4]:
# load json file
with open('./data/train.json') as data_file:
    train_data = json.load(data_file)

with open('./data/test.json') as data_file:
    test_data = json.load(data_file)

In [5]:
# get all ingredients in all dishes
def get_ingredients(json):
    raw_ingredients = list()
    for dish in json:
        for ingredient in dish['ingredients']:
            raw_ingredients.append(ingredient.strip())
    return raw_ingredients
raw_ingredients = list(set(get_ingredients(train_data)))
train_ingredients = collections.Counter(get_ingredients(train_data))
# get all cusines

def get_cuisine(json):
    raw_cuisines = list()
    for dish in json:
        raw_cuisines.append(dish['cuisine'].strip())
    return raw_cuisines
raw_cuisines = list(set(get_cuisine(train_data)))
train_cuisines =  collections.Counter(get_cuisine(train_data))

In [6]:
number_of_ingredients = len(train_ingredients)
print("number of ingredients:", number_of_ingredients)
number_of_train_dishes = len(train_data)
print("number of trainning dishes:", number_of_train_dishes )
number_of_test_dishes = len(test_data)
print("number of testing dishes:", number_of_test_dishes)

number of ingredients: 6714
number of trainning dishes: 39774
number of testing dishes: 9944


In [7]:
# rows = dishes
# cols = ingredients
model_matrix = np.zeros((number_of_train_dishes, number_of_ingredients))

In [8]:
for row, dish in enumerate(train_data):
    ingredients = dish['ingredients']
    for ingredient in ingredients:
        col = raw_ingredients.index(ingredient)
        model_matrix[row, col] = 1

In [24]:
features = model_matrix[:10000]
target = [raw_cuisines.index(dish['cuisine']) for dish in train_data][:10000]

In [25]:
train_X, test_X, train_y, test_y = model_selection.train_test_split(features, target, random_state=0)

In [26]:
print(train_X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
model = svm.SVC()
model.fit(train_X, train_y)

In [ ]:
print('train score: {}'.format(model.score(train_X, train_y)))
print('test score: {}'.format(model.score(test_X, test_y)))